# Generated by Django 6.0.2 on 2026-02-28 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('factory', 'Factory Overview'), ('production', 'Production Line'), ('showroom', 'Showroom'), ('video', 'Intro Video')], max_length=50)),
                ('file', models.FileField(upload_to='company_media/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='companies.company')),
            ],
        ),
    ]
