# Generated by Django 6.0.2 on 2026-02-28 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('business_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('trading', 'Trading Company'), ('wholesaler', 'Wholesaler')], max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('established_year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('factory_size', models.CharField(blank=True, max_length=100)),
                ('total_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_output_value', models.CharField(blank=True, max_length=100)),
                ('main_markets', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
