# Generated by Django 6.0 on 2026-03-17 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_type', models.CharField(choices=[('registration', 'Registration Fee'), ('monthly', 'Monthly Fee'), ('books', 'Books Fee'), ('other', 'Other')], max_length=20)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
